name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - name: Restore dependencies
      run: dotnet restore src/AzTableImport/AzTableImport.csproj

    - name: Build/Publish Win10
      run: dotnet publish -c Release -r win10-x64 /p:Version=$BUILD_NUMBER src/AzTableImport/AzTableImport.csproj

    - name: Build/Publish Linux
      run: dotnet publish -c Release -r linux-x64 /p:Version=$BUILD_NUMBER src/AzTableImport/AzTableImport.csproj

    - uses: actions/upload-artifact@v2
      with:
        name: net6-managed-$BUILD_NUMBER-win10
        path: src/AzTableImport/bin/Release/net6.0/win10-x64/publish/
    - uses: actions/upload-artifact@v2
      with:
        name: net6-managed-$BUILD_NUMBER-linux
        path: src/AzTableImport/bin/Release/net6.0/linux-x64/publish/
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
