name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.2.21155.3

    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - name: Restore dependencies
      run: dotnet restore src/AzTableImport/AzTableImport.csproj
    - name: Build
      run: dotnet build -c Release /p:Version=$BUILD_NUMBER src/AzTableImport/AzTableImport.csproj
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
